services:
  - type: web
    name: heart-disease-prediction
    env: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install --no-build-isolation -r requirements.txt
      npm install
      npm run build
    startCommand: python app.py 